export const SYMPTOM_SUGGESTION = [
    'headache',
    'fever',
    'sore throat',
    'runny nose',
    'cough',
    'chest pain',
    'shortness of breath',
    'nausea',
    'vomiting',
    'diarrhea',
    'body ache',
    'fatigue',
    'loss of appetite',
    'dizziness',
    'rash',
    'blurred vision',
    'back pain',
    'joint pain',
    'abdominal pain',
    'chills',
    'loss of taste',
    'loss of smell',
];